module.exports = {
  AVAILABLE_ACTIONS: 'Available actions:',
  VIEW_AVAILABLE_ACTIONS: 'To view the list of available actions, use the command /actions.',
  VIEW_TICKETS: '🎫 Your tickets',
  VIEW_PENDING_TICKETS: '🕐 Current pending tickets',
  CHANGE_LANGUAGE: '🌐 Change language',
  WELCOME_MESSAGE: 'Welcome! Thank you for using our bot.\n\nTo get started, enter the command /login to begin the authentication process.\n\nIf you have any questions or need assistance, feel free to ask. Happy using! 🤖✨',
  NOT_AUTHENTICATED: 'You need to be authenticated to perform this operation. Please enter the command /login to start the authentication process.',
  ENTER_LOGIN: 'Please enter your login:',
  ENTER_PASSWORD: 'Now enter your password:',
  INVALID_CREDENTIALS: 'Invalid login or password. Please try again.',
  YOUR_TICKETS: 'Your tickets:',
  NO_TICKETS: 'You have no tickets.',
  PENDING_TICKETS: 'Current pending tickets:',
  NO_PENDING_TICKETS: 'No current pending tickets.',
  ACCESS_DENIED: 'You do not have access to this command.',
  ERROR: 'An error occurred. Please try again later.',
  LANGUAGE_PROMPT: 'Please select your language:',
  LANGUAGE_SET_TO_RU: 'Language set to Russian.',
  LANGUAGE_SET_TO_EN: 'Language set to English.',
};
